"""
consume-basic.py — Flow A: Consume a built-in template

End-to-end example: BasicTemplate with a table and an image.

Run from the repo root:
    python skills/typy/examples/consume-basic.py
Then verify:
    typy verify /tmp/consume-basic.pdf
"""

from pathlib import Path

from typy.builder import DocumentBuilder
from typy.content import Content
from typy.functions import Block, Figure, Image, Table
from typy.markup import Text
from typy.templates import BasicTemplate

# ── 1. Create the builder ──────────────────────────────────────────────────
builder = DocumentBuilder()

repo_root = Path(__file__).resolve().parents[3]

# ── 2. Register assets BEFORE constructing Content that references them ────
#       add_file copies the file into the build directory and returns the
#       relative path that Typst can resolve.
img_path = builder.add_file(repo_root / "examples" / "basic" / "example.png")

# ── 3. Build the body ──────────────────────────────────────────────────────
body = Block(
    Content(
        [
            Text("Introduction: This document was generated by typy."),
            Figure(
                Image(img_path),
                caption="Example figure",
            ),
            Figure(
                Table(
                    {
                        "Quarter": {0: "Q1", 1: "Q2", 2: "Q3", 3: "Q4"},
                        "Revenue": {0: 120, 1: 145, 2: 130, 3: 160},
                    }
                ),
                caption="Quarterly revenue",
            ),
            Text("Conclusion: Results are positive across all quarters."),
        ]
    )
)

# ── 4. Construct the template dataclass ────────────────────────────────────
template = BasicTemplate(
    title="Quarterly Report",
    date="2024-01-01",
    author="Jane Doe",
    body=body,
)

# ── 5. Render ──────────────────────────────────────────────────────────────
output_path = Path("/tmp/consume-basic.pdf")
builder.add_template(template).save_pdf(output_path)
print(f"PDF saved to {output_path}")
