"""Unit tests for typy.verify – post-render PDF verification checks."""

from __future__ import annotations

import json
import re
from pathlib import Path
from unittest.mock import patch

import pytest
from typer.testing import CliRunner as _CliRunner

from typy.verify import (
    SEVERITY_ERROR,
    SEVERITY_WARNING,
    FontPolicyConfig,
    PageCountConfig,
    PlaceholderConfig,
    VerificationConfig,
    VerificationDiagnostic,
    VerificationResult,
    _count_pdf_pages,
    _extract_pdf_fonts,
    _extract_pdf_text,
    check_font_policy,
    check_overflow,
    check_page_count,
    check_placeholders,
    verify_pdf,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_pdf(*, pages: int = 1, fonts: list[str] | None = None, extra: bytes = b"") -> bytes:
    """Build a minimal fake PDF byte string for unit-testing the parsers.

    The generated bytes contain just enough structure for the individual
    check functions to parse:

    * ``/Count N`` for page-count detection.
    * ``/BaseFont /Name`` entries for font detection.
    * ``/MediaBox [0 0 612 792]`` for overflow detection.
    * Passthrough of any ``extra`` bytes (e.g. BT/ET text blocks).
    """
    parts: list[bytes] = [
        f"/Count {pages}".encode(),
        b"/MediaBox [0 0 612 792]",
    ]
    for font in fonts or []:
        parts.append(f"/BaseFont /{font}".encode())
    parts.append(extra)
    return b"\n".join(parts)


def _make_pdf_with_text(text: str) -> bytes:
    """Return a fake PDF with a BT/ET block containing *text*."""
    encoded = text.encode("latin-1", errors="replace")
    bt_block = b"BT (" + encoded + b") Tj ET"
    return _make_pdf(extra=bt_block)


def _make_pdf_with_large_page(width: float = 6000.0, height: float = 9000.0) -> bytes:
    """Return a fake PDF with an oversized MediaBox."""
    return (
        f"/Count 1\n/MediaBox [0 0 {width:.0f} {height:.0f}]"
    ).encode()


# ---------------------------------------------------------------------------
# _count_pdf_pages
# ---------------------------------------------------------------------------


def test_count_pdf_pages_single():
    data = b"/Count 1"
    assert _count_pdf_pages(data) == 1


def test_count_pdf_pages_multi():
    data = b"/Count 42"
    assert _count_pdf_pages(data) == 42


def test_count_pdf_pages_nested_takes_max():
    # Nested page trees: take the largest /Count (document-level)
    data = b"/Count 3 /Count 10 /Count 7"
    assert _count_pdf_pages(data) == 10


def test_count_pdf_pages_no_count():
    data = b"%PDF-1.4 no page tree here"
    assert _count_pdf_pages(data) is None


# ---------------------------------------------------------------------------
# _extract_pdf_fonts
# ---------------------------------------------------------------------------


def test_extract_pdf_fonts_single():
    data = b"/BaseFont /Helvetica"
    assert _extract_pdf_fonts(data) == {"Helvetica"}


def test_extract_pdf_fonts_multiple():
    data = b"/BaseFont /Helvetica\n/BaseFont /Times-Roman"
    assert _extract_pdf_fonts(data) == {"Helvetica", "Times-Roman"}


def test_extract_pdf_fonts_strips_subset_prefix():
    data = b"/BaseFont /ABCDEF+DejaVuSerif"
    assert _extract_pdf_fonts(data) == {"DejaVuSerif"}


def test_extract_pdf_fonts_no_fonts():
    data = b"%PDF-1.4 no fonts here"
    assert _extract_pdf_fonts(data) == set()


# ---------------------------------------------------------------------------
# _extract_pdf_text
# ---------------------------------------------------------------------------


def test_extract_pdf_text_literal_string():
    data = b"BT (Hello World) Tj ET"
    text = _extract_pdf_text(data)
    assert "Hello World" in text


def test_extract_pdf_text_no_bt_block():
    data = b"some binary data without BT blocks"
    text = _extract_pdf_text(data)
    assert text == ""


def test_extract_pdf_text_multiple_blocks():
    data = b"BT (foo) Tj ET ... BT (bar) Tj ET"
    text = _extract_pdf_text(data)
    assert "foo" in text
    assert "bar" in text


# ---------------------------------------------------------------------------
# VerificationDiagnostic
# ---------------------------------------------------------------------------


def test_diagnostic_str_without_hint():
    d = VerificationDiagnostic(
        code="VFY_E001", check="placeholders", severity="error", message="test msg"
    )
    s = str(d)
    assert "VFY_E001" in s
    assert "ERROR" in s
    assert "test msg" in s
    assert "Hint" not in s


def test_diagnostic_str_with_hint():
    d = VerificationDiagnostic(
        code="VFY_E002",
        check="page_count",
        severity="warning",
        message="test",
        hint="do something",
    )
    s = str(d)
    assert "Hint: do something" in s


def test_diagnostic_to_dict_includes_code_severity_message():
    d = VerificationDiagnostic(
        code="VFY_E003", check="font_policy", severity="error", message="boom"
    )
    d_dict = d.to_dict()
    assert d_dict["code"] == "VFY_E003"
    assert d_dict["check"] == "font_policy"
    assert d_dict["severity"] == "error"
    assert d_dict["message"] == "boom"
    assert "hint" not in d_dict  # omitted when empty


def test_diagnostic_to_dict_includes_hint_when_present():
    d = VerificationDiagnostic(
        code="VFY_E004", check="overflow", severity="warning",
        message="m", hint="h"
    )
    assert d.to_dict()["hint"] == "h"


# ---------------------------------------------------------------------------
# VerificationResult
# ---------------------------------------------------------------------------


def test_result_passed_when_no_errors():
    result = VerificationResult(
        Path("out.pdf"),
        [
            VerificationDiagnostic(
                code="VFY_E004", check="overflow", severity=SEVERITY_WARNING,
                message="warn"
            )
        ],
    )
    assert result.passed is True


def test_result_failed_when_error_present():
    result = VerificationResult(
        Path("out.pdf"),
        [
            VerificationDiagnostic(
                code="VFY_E001", check="placeholders", severity=SEVERITY_ERROR,
                message="err"
            )
        ],
    )
    assert result.passed is False


def test_result_errors_and_warnings_split():
    diags = [
        VerificationDiagnostic(
            code="VFY_E001", check="placeholders", severity=SEVERITY_ERROR, message="e"
        ),
        VerificationDiagnostic(
            code="VFY_E004", check="overflow", severity=SEVERITY_WARNING, message="w"
        ),
    ]
    result = VerificationResult(Path("out.pdf"), diags)
    assert len(result.errors) == 1
    assert len(result.warnings) == 1


def test_result_to_dict_structure():
    result = VerificationResult(Path("out.pdf"), [])
    d = result.to_dict()
    assert d["pdf"] == "out.pdf"
    assert d["passed"] is True
    assert d["error_count"] == 0
    assert d["warning_count"] == 0
    assert d["diagnostics"] == []


# ---------------------------------------------------------------------------
# check_placeholders
# ---------------------------------------------------------------------------


def test_check_placeholders_clean_pdf(tmp_path):
    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf_with_text("Hello World"))
    diags = check_placeholders(pdf, PlaceholderConfig())
    assert diags == []


def test_check_placeholders_detects_double_brace(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("Dear {{author}}, welcome."))
    diags = check_placeholders(pdf, PlaceholderConfig())
    assert any(d.code == "VFY_E001" and d.severity == SEVERITY_ERROR for d in diags)
    assert any("{{author}}" in d.message for d in diags)


def test_check_placeholders_detects_angle_bracket(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("Company: <<COMPANY_NAME>>"))
    diags = check_placeholders(pdf, PlaceholderConfig())
    assert any("<<COMPANY_NAME>>" in d.message for d in diags)


def test_check_placeholders_detects_todo(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("Section TODO fix later"))
    diags = check_placeholders(pdf, PlaceholderConfig())
    assert any(d.code == "VFY_E001" for d in diags)


def test_check_placeholders_custom_pattern(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("REDACTED value here"))
    config = PlaceholderConfig(patterns=[r"REDACTED"])
    diags = check_placeholders(pdf, config)
    assert any("REDACTED" in d.message for d in diags)


def test_check_placeholders_missing_file():
    diags = check_placeholders(Path("/nonexistent/file.pdf"), PlaceholderConfig())
    assert len(diags) == 1
    assert diags[0].code == "VFY_E001"
    assert diags[0].severity == SEVERITY_ERROR


# ---------------------------------------------------------------------------
# check_page_count
# ---------------------------------------------------------------------------


def test_check_page_count_no_constraints_skips(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    diags = check_page_count(pdf, PageCountConfig())
    assert diags == []


def test_check_page_count_within_bounds(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=5))
    diags = check_page_count(pdf, PageCountConfig(min_pages=1, max_pages=10))
    assert diags == []


def test_check_page_count_below_minimum(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    diags = check_page_count(pdf, PageCountConfig(min_pages=3))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E002"
    assert diags[0].severity == SEVERITY_ERROR
    assert "1" in diags[0].message
    assert "3" in diags[0].message


def test_check_page_count_above_maximum(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=20))
    diags = check_page_count(pdf, PageCountConfig(max_pages=10))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E002"
    assert "20" in diags[0].message
    assert "10" in diags[0].message


def test_check_page_count_exactly_at_minimum(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=2))
    diags = check_page_count(pdf, PageCountConfig(min_pages=2))
    assert diags == []


def test_check_page_count_exactly_at_maximum(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=10))
    diags = check_page_count(pdf, PageCountConfig(max_pages=10))
    assert diags == []


def test_check_page_count_below_min_with_both_constraints(tmp_path):
    """Page count below min_pages is flagged even when max_pages is also set."""
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    # 1 page violates min=3; does not violate max=10
    diags = check_page_count(pdf, PageCountConfig(min_pages=3, max_pages=10))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E002"
    assert "1" in diags[0].message  # actual page count mentioned


def test_check_page_count_unreadable_count(tmp_path):
    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(b"no page count here")
    diags = check_page_count(pdf, PageCountConfig(min_pages=1))
    assert len(diags) == 1
    assert diags[0].severity == SEVERITY_WARNING


def test_check_page_count_missing_file():
    diags = check_page_count(Path("/nonexistent/file.pdf"), PageCountConfig(min_pages=1))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E002"
    assert diags[0].severity == SEVERITY_ERROR


# ---------------------------------------------------------------------------
# check_font_policy
# ---------------------------------------------------------------------------


def test_check_font_policy_no_constraints_skips(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["Helvetica"]))
    diags = check_font_policy(pdf, FontPolicyConfig())
    assert diags == []


def test_check_font_policy_allowed_fonts_passes(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["DejaVuSerif"]))
    diags = check_font_policy(pdf, FontPolicyConfig(allowed_fonts=["DejaVu"]))
    assert diags == []


def test_check_font_policy_disallowed_font(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["Arial"]))
    diags = check_font_policy(pdf, FontPolicyConfig(allowed_fonts=["DejaVu"]))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E003"
    assert diags[0].severity == SEVERITY_ERROR
    assert "Arial" in diags[0].message


def test_check_font_policy_required_font_present(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["DejaVuSerif", "DejaVuSans"]))
    diags = check_font_policy(pdf, FontPolicyConfig(required_fonts=["DejaVu"]))
    assert diags == []


def test_check_font_policy_required_font_missing(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["Helvetica"]))
    diags = check_font_policy(pdf, FontPolicyConfig(required_fonts=["DejaVu"]))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E003"
    assert "DejaVu" in diags[0].message


def test_check_font_policy_no_fonts_warning(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(b"no fonts here")
    diags = check_font_policy(pdf, FontPolicyConfig(required_fonts=["DejaVu"]))
    assert any(d.severity == SEVERITY_WARNING for d in diags)


def test_check_font_policy_case_insensitive(tmp_path):
    pdf = tmp_path / "f.pdf"
    pdf.write_bytes(_make_pdf(fonts=["DEJAVUSERIF"]))
    diags = check_font_policy(pdf, FontPolicyConfig(required_fonts=["dejavu"]))
    assert diags == []


def test_check_font_policy_missing_file():
    diags = check_font_policy(
        Path("/nonexistent/file.pdf"), FontPolicyConfig(required_fonts=["DejaVu"])
    )
    assert len(diags) == 1
    assert diags[0].code == "VFY_E003"
    assert diags[0].severity == SEVERITY_ERROR


# ---------------------------------------------------------------------------
# check_overflow
# ---------------------------------------------------------------------------


def test_check_overflow_normal_page(tmp_path):
    pdf = tmp_path / "o.pdf"
    pdf.write_bytes(_make_pdf())  # default 612×792 pts (letter)
    diags = check_overflow(pdf)
    assert diags == []


def test_check_overflow_large_page_triggers_warning(tmp_path):
    pdf = tmp_path / "o.pdf"
    pdf.write_bytes(_make_pdf_with_large_page(width=8500, height=11000))
    diags = check_overflow(pdf)
    assert len(diags) == 1
    assert diags[0].code == "VFY_E004"
    assert diags[0].severity == SEVERITY_WARNING
    assert "8500" in diags[0].message


def test_check_overflow_just_at_threshold(tmp_path):
    """Exactly 5000 pts is allowed; only strictly above triggers a warning."""
    pdf = tmp_path / "o.pdf"
    pdf.write_bytes(b"/MediaBox [0 0 5000 5000]")
    diags = check_overflow(pdf)
    assert diags == []


def test_check_overflow_just_above_threshold(tmp_path):
    pdf = tmp_path / "o.pdf"
    pdf.write_bytes(b"/MediaBox [0 0 5001 842]")
    diags = check_overflow(pdf)
    assert len(diags) == 1


def test_check_overflow_missing_file():
    diags = check_overflow(Path("/nonexistent/file.pdf"))
    assert len(diags) == 1
    assert diags[0].code == "VFY_E004"
    assert diags[0].severity == SEVERITY_ERROR


# ---------------------------------------------------------------------------
# verify_pdf – integration
# ---------------------------------------------------------------------------


def test_verify_pdf_default_config_passes_clean_pdf(tmp_path):
    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf(pages=1, fonts=["Helvetica"]))
    result = verify_pdf(pdf)
    assert result.passed is True
    assert result.pdf_path == pdf


def test_verify_pdf_page_count_failure(tmp_path):
    pdf = tmp_path / "short.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    config = VerificationConfig(page_count=PageCountConfig(min_pages=5))
    result = verify_pdf(pdf, config)
    assert not result.passed
    assert any(d.code == "VFY_E002" for d in result.errors)


def test_verify_pdf_font_policy_failure(tmp_path):
    pdf = tmp_path / "bad_fonts.pdf"
    pdf.write_bytes(_make_pdf(fonts=["Arial"]))
    config = VerificationConfig(font_policy=FontPolicyConfig(allowed_fonts=["DejaVu"]))
    result = verify_pdf(pdf, config)
    assert not result.passed
    assert any(d.code == "VFY_E003" for d in result.errors)


def test_verify_pdf_placeholder_failure(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("Hello {{name}}, welcome!"))
    result = verify_pdf(pdf)
    assert not result.passed
    assert any(d.code == "VFY_E001" for d in result.errors)


def test_verify_pdf_none_config_uses_defaults(tmp_path):
    pdf = tmp_path / "x.pdf"
    pdf.write_bytes(_make_pdf())
    result = verify_pdf(pdf, None)
    # Should not raise; result is a VerificationResult
    assert isinstance(result, VerificationResult)


def test_verify_pdf_disabled_check_not_run(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("{{unresolved}}"))
    config = VerificationConfig(checks={"placeholders": False, "page_count": False,
                                         "font_policy": False, "overflow": False})
    result = verify_pdf(pdf, config)
    assert result.passed is True
    assert result.diagnostics == []


def test_verify_pdf_to_dict_is_json_serialisable(tmp_path):
    pdf = tmp_path / "x.pdf"
    pdf.write_bytes(_make_pdf())
    result = verify_pdf(pdf)
    # Must not raise
    serialised = json.dumps(result.to_dict())
    parsed = json.loads(serialised)
    assert "passed" in parsed
    assert "diagnostics" in parsed


# ---------------------------------------------------------------------------
# VerificationConfig
# ---------------------------------------------------------------------------


def test_verification_config_defaults():
    vc = VerificationConfig()
    assert vc.checks.get("placeholders", True) is True
    assert vc.checks.get("page_count", True) is True
    assert vc.checks.get("font_policy", True) is True
    assert vc.checks.get("overflow", True) is True


def test_verification_config_from_json():
    raw = json.dumps({
        "page_count": {"min_pages": 2, "max_pages": 50},
        "font_policy": {"required_fonts": ["DejaVu"]},
        "checks": {"overflow": False},
    })
    vc = VerificationConfig.model_validate_json(raw)
    assert vc.page_count.min_pages == 2
    assert vc.page_count.max_pages == 50
    assert vc.font_policy.required_fonts == ["DejaVu"]
    assert vc.checks["overflow"] is False


# ---------------------------------------------------------------------------
# Template.verification_config class variable
# ---------------------------------------------------------------------------


def test_template_base_class_has_verification_config():
    from typy.templates import Template

    assert hasattr(Template, "verification_config")
    assert Template.verification_config is None


def test_template_subclass_can_set_verification_config():
    from typy.templates import BasicTemplate
    from typy.verify import PageCountConfig, VerificationConfig

    class MyTemplate(BasicTemplate):
        verification_config = VerificationConfig(
            page_count=PageCountConfig(min_pages=2)
        )

    assert MyTemplate.verification_config is not None
    assert MyTemplate.verification_config.page_count.min_pages == 2
    # Should not affect the base class
    assert BasicTemplate.verification_config is None


# ---------------------------------------------------------------------------
# CLI: cmd_verify
# ---------------------------------------------------------------------------


_runner = _CliRunner()


def _build_app():
    from typy.cli import _build_app as _ba
    return _ba()


def test_cmd_verify_passes_clean_pdf(tmp_path):
    from typy.cli import cmd_verify

    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf(pages=2))
    # Should not raise / exit
    cmd_verify(pdf_path=pdf)


def test_cmd_verify_missing_pdf_exits_1(tmp_path):
    from typy.cli import cmd_verify

    with pytest.raises(SystemExit) as exc:
        cmd_verify(pdf_path=tmp_path / "missing.pdf")
    assert exc.value.code == 1


def test_cmd_verify_json_output(tmp_path, capsys):
    from typy.cli import cmd_verify

    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    cmd_verify(pdf_path=pdf, as_json=True)
    captured = capsys.readouterr()
    parsed = json.loads(captured.out)
    assert "passed" in parsed
    assert "diagnostics" in parsed


def test_cmd_verify_exits_2_on_error(tmp_path):
    from typy.cli import cmd_verify

    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("{{unresolved}}"))
    with pytest.raises(SystemExit) as exc:
        cmd_verify(pdf_path=pdf)
    assert exc.value.code == 2


def test_cmd_verify_with_config_file(tmp_path):
    from typy.cli import cmd_verify

    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=3))
    config_data = {"page_count": {"min_pages": 1, "max_pages": 5}}
    config_file = tmp_path / "vc.json"
    config_file.write_text(json.dumps(config_data), encoding="utf-8")

    # Should pass without error
    cmd_verify(pdf_path=pdf, config_file=config_file)


def test_cmd_verify_missing_config_file_exits_1(tmp_path):
    from typy.cli import cmd_verify

    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    with pytest.raises(SystemExit) as exc:
        cmd_verify(pdf_path=pdf, config_file=tmp_path / "missing.json")
    assert exc.value.code == 1


def test_cmd_verify_invalid_config_file_exits_1(tmp_path):
    from typy.cli import cmd_verify

    pdf = tmp_path / "p.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    bad_config = tmp_path / "bad.json"
    bad_config.write_text("{bad json}", encoding="utf-8")
    with pytest.raises(SystemExit) as exc:
        cmd_verify(pdf_path=pdf, config_file=bad_config)
    assert exc.value.code == 1


# CLI invocation via typer runner


def test_main_verify_help():
    app = _build_app()
    result = _runner.invoke(app, ["verify", "--help"])
    assert result.exit_code == 0
    plain = re.sub(r"\x1b\[[0-9;]*m", "", result.output)
    assert "--config" in plain
    assert "--format" in plain


def test_main_verify_passes(tmp_path):
    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    app = _build_app()
    result = _runner.invoke(app, ["verify", str(pdf)])
    assert result.exit_code == 0


def test_main_verify_json_format(tmp_path):
    pdf = tmp_path / "clean.pdf"
    pdf.write_bytes(_make_pdf(pages=1))
    app = _build_app()
    result = _runner.invoke(app, ["verify", str(pdf), "--format", "json"])
    assert result.exit_code == 0
    parsed = json.loads(result.output)
    assert "passed" in parsed


def test_main_verify_exits_2_on_failure(tmp_path):
    pdf = tmp_path / "ph.pdf"
    pdf.write_bytes(_make_pdf_with_text("{{unresolved}}"))
    app = _build_app()
    result = _runner.invoke(app, ["verify", str(pdf)])
    assert result.exit_code == 2


def test_main_verify_missing_pdf_exits_1(tmp_path):
    app = _build_app()
    result = _runner.invoke(app, ["verify", str(tmp_path / "missing.pdf")])
    assert result.exit_code == 1


# ---------------------------------------------------------------------------
# CLI: render --verify
# ---------------------------------------------------------------------------


def test_render_verify_flag_calls_verify_pdf(tmp_path):
    """--verify causes verify_pdf to be called after saving the PDF."""
    from typy.cli import cmd_render
    from typy.verify import VerificationResult

    md = tmp_path / "notes.md"
    md.write_text("# Hello", encoding="utf-8")
    output = tmp_path / "notes.pdf"

    with patch("typy.builder.DocumentBuilder.save_pdf"):
        with patch("typy.verify.verify_pdf") as mock_verify:
            mock_verify.return_value = VerificationResult(output, [])
            cmd_render(
                template=None,
                data_file=None,
                markdown_file=md,
                output=output,
                verify=True,
            )

    mock_verify.assert_called_once()


def test_render_no_verify_flag_does_not_call_verify_pdf(tmp_path):
    """Without --verify, verify_pdf is not called."""
    from typy.cli import cmd_render

    md = tmp_path / "notes.md"
    md.write_text("# Hello", encoding="utf-8")
    output = tmp_path / "notes.pdf"

    with patch("typy.builder.DocumentBuilder.save_pdf"):
        with patch("typy.verify.verify_pdf") as mock_verify:
            cmd_render(
                template=None,
                data_file=None,
                markdown_file=md,
                output=output,
                verify=False,
            )

    mock_verify.assert_not_called()


def test_render_verify_exits_2_on_failure(tmp_path):
    """When verify_pdf returns failures, cmd_render exits with code 2."""
    from typy.cli import cmd_render
    from typy.verify import VerificationResult

    md = tmp_path / "notes.md"
    md.write_text("# Hello", encoding="utf-8")
    output = tmp_path / "notes.pdf"

    error_diag = VerificationDiagnostic(
        code="VFY_E001", check="placeholders", severity=SEVERITY_ERROR, message="fail"
    )

    with patch("typy.builder.DocumentBuilder.save_pdf"):
        with patch("typy.verify.verify_pdf") as mock_verify:
            mock_verify.return_value = VerificationResult(output, [error_diag])
            with pytest.raises(SystemExit) as exc:
                cmd_render(
                    template=None,
                    data_file=None,
                    markdown_file=md,
                    output=output,
                    verify=True,
                )

    assert exc.value.code == 2


def test_render_verify_with_verify_config_file(tmp_path):
    """--verify-config loads config from JSON and passes it to verify_pdf."""
    from typy.cli import cmd_render
    from typy.verify import VerificationResult

    md = tmp_path / "notes.md"
    md.write_text("# Hello", encoding="utf-8")
    output = tmp_path / "notes.pdf"
    vc_file = tmp_path / "vc.json"
    vc_file.write_text(
        json.dumps({"page_count": {"min_pages": 1}}), encoding="utf-8"
    )

    with patch("typy.builder.DocumentBuilder.save_pdf"):
        with patch("typy.verify.verify_pdf") as mock_verify:
            mock_verify.return_value = VerificationResult(output, [])
            cmd_render(
                template=None,
                data_file=None,
                markdown_file=md,
                output=output,
                verify=True,
                verify_config_file=vc_file,
            )

    mock_verify.assert_called_once()
    called_config = mock_verify.call_args[0][1]
    assert called_config.page_count.min_pages == 1


def test_render_verify_missing_config_file_exits_1(tmp_path):
    from typy.cli import cmd_render

    md = tmp_path / "notes.md"
    md.write_text("# Hello", encoding="utf-8")
    output = tmp_path / "notes.pdf"

    with patch("typy.builder.DocumentBuilder.save_pdf"):
        with pytest.raises(SystemExit) as exc:
            cmd_render(
                template=None,
                data_file=None,
                markdown_file=md,
                output=output,
                verify=True,
                verify_config_file=tmp_path / "missing.json",
            )

    assert exc.value.code == 1
