name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '1.8.5'

      - name: Install dependencies
        run: poetry install --with dev,tests

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure